spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/elifoot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true

  flyway:
    enabled: true