spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/elifoot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true;

  flyway:
    enabled: true

jwt:
  public:
    key: classpath:authz.pub
  private:
    key: classpath:authz.pem